### ISSUE TITLE
cutils module

### ISSUE THREAD

**Issue by StarMi0** [czq142857/NMC#4]
Traceback (most recent call last):
  File "main.py", line 494, in <module>
    import cutils
ModuleNotFoundError: No module named 'cutils'

Can help? Where I can get that module?

**Comment by czq142857** [comment]
```
python setup.py build_ext --inplace
```

Please read the instructions in the readme file carefully.

**Comment by StarMi0** [comment]
it works in virtualenv?

**Comment by czq142857** [comment]
It should be, as long as Cython works in virtualenv.
