### ISSUE TITLE
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by StarMi0** [czq142857/NMC#5]
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
When run testmode

**Comment by StarMi0** [comment]
yTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2080 Ti
Nvidia driver version: 515.65.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.23.2
[pip3] torch==1.8.0
[conda] Could not collect

**Comment by czq142857** [comment]
This is an issue of your environment. I cannot help you debug.
Please make sure your pytorch is installed correctly and supports cuda+cudnn.

**Comment by StarMi0** [comment]
just reinstalled all libraries with new options, but thanks for the help anyway
