### ISSUE TITLE
The generalizability

### ISSUE THREAD

**Issue by Zhuyouxx** [czq142857/NMC#6]
Hello,ZHIQIN CHEN.
Thank you for such a wonderful job!
I have recently been working on a surface reconstruction,but the use of mc does not work well.

Q : Can I use your network and weights directly to do surface reconstruction on my data?
The only data I have available are the Signed Distance Field.

Thanks!

**Comment by czq142857** [comment]
Sure, please give it a try. The pre-trained weights were trained only on clean data though, so if your data contains noise, you might have to train the network from scratch on noisy data.

**Comment by Zhuyouxx** [comment]
Great!Do I need to process my sdf data before committing to the network?Or can I just put it in directly when generating .hdf5?

**Comment by czq142857** [comment]
Please read the code of the testing function for details. You can get the results as long as you convert your data into a 3D grid of signed distances and use the provided code to process it.

**Comment by Zhuyouxx** [comment]
Got it.Thank you for such a prompt response！
