### ISSUE TITLE
Train with Shapenet

### ISSUE THREAD

**Issue by ZiAngGu1** [czq142857/NMC#7]
Thanks for the wonderful work.
 As you mentioned in the training process, the shapenet is not an option since the mesh are not in closed triangles. However, it there any way that I could convert the mesh in shapenet to closed triangle mesh?
Thank you so much for your time!

**Comment by czq142857** [comment]
Sorry, I do not know a way to convert the meshes in ShapeNet to closed triangle meshes while keeping the sharp geometric features.

If you are okay with re-meshing (gives you smoothed shapes), you can try https://github.com/davidstutz/mesh-fusion.

**Comment by ZiAngGu1** [comment]
Sure, I will give it a try,
Thank you for your time!
